version: 2
enable-beta-ecosystems: true
updates:
  # Workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Workspace pubspec.yaml
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  # Packages
  # - package-ecosystem: "pub"
  #   directory: "/packages/halildurmus_hooks"
  #   schedule:
  #     interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/halildurmus_lints"
    schedule:
      interval: "weekly"
