name: tools_workspace
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  # - packages/halildurmus_hooks
  - packages/halildurmus_lints
  - packages/next_version

dev_dependencies:
  halildurmus_lints: ^1.1.0
