name: next_version
description: A package that determines the next package version by analyzing
  conventional commits.
publish_to: none
repository: https://github.com/halildurmus/tools/tree/main/packages/next_version

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  conventional_commit: ^0.6.1+1
  version: ^3.0.2

dev_dependencies:
  checks: ^0.3.1
  halildurmus_lints: ^1.1.0
  test: ^1.29.0
