name: Prepare Release (halildurmus_lints)

on:
  workflow_dispatch:

jobs:
  prepare-release:
    uses: halildurmus/workflows/.github/workflows/prepare_release.yml@main
    with:
      update_changelog_args: '--include-path "packages/halildurmus_lints/**/*" --repository "../../"'
      working_directory: packages/halildurmus_lints
    secrets:
      token: ${{ secrets.PAT }}
